import React, { Fragment } from "react";
import MainNavigation from "@/components/layout/main-navigation";
import Head from "next/head";

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <Fragment>
      <Head>
        <title>Oat's Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNavigation />
      <main>{children}</main>
    </Fragment>
  );
};

export default Layout;
