import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { Fragment } from "react";
import Hero from "@/components/hero";
import FeaturedPosts from "@/components/featured-posts";
import IPost from "@/model/post";
// import { DUMMY_POSTS } from "@/data/post-dummy-data";
import { getFeaturedPosts } from "@/utils/posts-util";

type Props = {
  posts: IPost[];
};

const inter = Inter({ subsets: ["latin"] });

export default function HomePage(props: Props) {
  const { posts } = props;

  return (
    <Fragment>
      <Head>
        <title>Oat's Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Hero />
        <FeaturedPosts posts={posts} />
      </main>
    </Fragment>
  );
}

export const getStaticProps = async () => {
  const featuredPosts = getFeaturedPosts();

  return {
    props: {
      posts: JSON.parse(JSON.stringify(featuredPosts)),
    },
    revalidate: 1800,
  };
};
